## Описание исследования
Компания купила крупный сервис для чтения книг по подписке. Необходимо провести исследование по анализу базы данных сервиса.

**Цель исследования:**  
проанализировать базу данных с целью формулировки ценностного предложения для нового продукта

**Ход исследования:**
1. Загрузка и исследование предложенных таблиц
2. Написание и выполнение SQL-запросов
3. Описание выводов по итогам выполнения запросов
4. Формирование общего вывода

## Исследование таблиц
База данных содержит таблицы с информацией о книгах, издательствах, авторах, а также пользовательские обзоры книг. Начнем с просмотра таблиц.

In [1]:
# импортируем библиотеки
import pandas as pd
from sqlalchemy import text, create_engine

# устанавливаем параметры
db_config = {'user': 'praktikum_student', # имя пользователя
'pwd': 'Sdf4$2;d-d30pp', # пароль
'host': 'rc1b-wcoijxj3yxfsf3fs.mdb.yandexcloud.net',
'port': 6432, # порт подключения
'db': 'data-analyst-final-project-db'} # название базы данных
connection_string = 'postgresql://{user}:{pwd}@{host}:{port}/{db}'.format(**db_config)

# сохраняем коннектор
engine = create_engine(connection_string, connect_args={'sslmode':'require'})

### **Таблица `books`**

Содержит данные о книгах:

- `book_id` — идентификатор книги;
- `author_id` — идентификатор автора;
- `title` — название книги;
- `num_pages` — количество страниц;
- `publication_date` — дата публикации книги;
- `publisher_id` — идентификатор издателя.

Выведем первые 5 строк таблицы.

In [2]:
# чтобы выполнить SQL-запрос, используем Pandas
query = '''SELECT * 
           FROM books 
           LIMIT 5
        '''

con=engine.connect()

pd.io.sql.read_sql(sql=text(query), con = con)

book_id  author_id                                              title  \
0        1        546                                       'Salem's Lot   
1        2        465                 1 000 Places to See Before You Die   
2        3        407  13 Little Blue Envelopes (Little Blue Envelope...   
3        4         82  1491: New Revelations of the Americas Before C...   
4        5        125                                               1776   

   num_pages publication_date  publisher_id  
0        594       2005-11-01            93  
1        992       2003-05-22           336  
2        322       2010-12-21           135  
3        541       2006-10-10           309  
4        386       2006-07-04           268

### **Таблица `authors`**

Содержит данные об авторах:

- `author_id` — идентификатор автора;
- `author` — имя автора.

Выведем первые 5 строк таблицы.

In [3]:
# чтобы выполнить SQL-запрос, используем Pandas
query = '''SELECT * 
           FROM authors 
           LIMIT 5'''

con=engine.connect()

pd.io.sql.read_sql(sql=text(query), con = con)

author_id                          author
0          1                      A.S. Byatt
1          2  Aesop/Laura Harris/Laura Gibbs
2          3                 Agatha Christie
3          4                   Alan Brennert
4          5        Alan Moore/David   Lloyd

### **Таблица `publishers`**

Содержит данные об издательствах:

- `publisher_id` — идентификатор издательства;
- `publisher` — название издательства.

Выведем первые 5 строк таблицы.

In [4]:
# чтобы выполнить SQL-запрос, используем Pandas
query = '''SELECT * 
           FROM publishers 
           LIMIT 5'''

con=engine.connect()

pd.io.sql.read_sql(sql=text(query), con = con)

publisher_id                          publisher
0             1                                Ace
1             2                           Ace Book
2             3                          Ace Books
3             4                      Ace Hardcover
4             5  Addison Wesley Publishing Company

### **Таблица `ratings`**

Содержит данные о пользовательских оценках книг:

- `rating_id` — идентификатор оценки;
- `book_id` — идентификатор книги;
- `username` — имя пользователя, оставившего оценку;
- `rating` — оценка книги.

Выведем первые 5 строк таблицы.

In [5]:
# чтобы выполнить SQL-запрос, используем Pandas
query = '''SELECT * 
           FROM ratings 
           LIMIT 5'''

con=engine.connect()

pd.io.sql.read_sql(sql=text(query), con = con)

rating_id  book_id       username  rating
0          1        1     ryanfranco       4
1          2        1  grantpatricia       2
2          3        1   brandtandrea       5
3          4        2       lorichen       3
4          5        2    mariokeller       2

### **Таблица `reviews`**

Содержит данные о пользовательских обзорах на книги:

- `review_id` — идентификатор обзора;
- `book_id` — идентификатор книги;
- `username` — имя пользователя, написавшего обзор;
- `text` — текст обзора.

Выведем первые 5 строк таблицы.

In [6]:
# чтобы выполнить SQL-запрос, используем Pandas
query = '''SELECT * 
           FROM reviews 
           LIMIT 5'''

con=engine.connect()

pd.io.sql.read_sql(sql=text(query), con = con)

review_id  book_id       username  \
0          1        1   brandtandrea   
1          2        1     ryanfranco   
2          3        2       lorichen   
3          4        3  johnsonamanda   
4          5        3    scotttamara   

                                                text  
0  Mention society tell send professor analysis. ...  
1  Foot glass pretty audience hit themselves. Amo...  
2  Listen treat keep worry. Miss husband tax but ...  
3  Finally month interesting blue could nature cu...  
4  Nation purpose heavy give wait song will. List...

## Выполнение SQL-запросов
### Количество книг, которые вышли после 1 января 2000 года
**Вывод:** 
- После 1 января 2000 года вышло 819 книг. 

In [7]:
# чтобы выполнить SQL-запрос, используем Pandas
query = '''
           SELECT count(book_id) "Количество книг"
           FROM books 
           WHERE publication_date > '2000-01-01' 
        '''

con=engine.connect()

pd.io.sql.read_sql(sql=text(query), con = con)

Количество книг
0              819

### Количество обзоров и средняя оценка для каждой книги
**Вывод:** 
- Всего в базе представлено 1000 книг. 
- Самое большое количество обзоров написано для книги Twilight (7 обзоров). Ее средняя оценка - 3.66.
- Далее идут 14 книг с количеством обзоров равным 6. Среди них книги с самым высоким рейтингом это:
    - Harry Potter and the Prisoner of Azkaban — 4.41
    - Harry Potter and the Chamber of Secrets — 4.29
    - The Book Thief — 4.26

In [8]:
# чтобы выполнить SQL-запрос, используем Pandas
query = '''
           SELECT b.title "Название книги",
                  COUNT(DISTINCT rev.review_id) "Количество обзоров", 
                  ROUND(AVG(rat.rating), 2) "Средняя оценка"
           FROM books b
           LEFT JOIN ratings rat ON b.book_id=rat.book_id 
           LEFT JOIN reviews rev ON b.book_id=rev.book_id
           GROUP BY b.book_id
           ORDER BY "Количество обзоров" DESC, "Средняя оценка" DESC
        '''

con=engine.connect()

pd.io.sql.read_sql(sql=text(query), con = con)

Название книги  Количество обзоров  \
0                              Twilight (Twilight  #1)                   7   
1    Harry Potter and the Prisoner of Azkaban (Harr...                   6   
2    Harry Potter and the Chamber of Secrets (Harry...                   6   
3                                       The Book Thief                   6   
4                                     The Glass Castle                   6   
..                                                 ...                 ...   
995  Disney's Beauty and the Beast (A Little Golden...                   0   
996                               Leonardo's Notebooks                   0   
997                          Essential Tales and Poems                   0   
998    Anne Rice's The Vampire Lestat: A Graphic Novel                   0   
999                            The Natural Way to Draw                   0   

     Средняя оценка  
0              3.66  
1              4.41  
2              4.29  
3              4.26  
4              4.21  
..              ...  
995            4.00  
996            4.00  
997            4.00  
998            3.67  
999            3.00  

[1000 rows x 3 columns]

### Издательство, которое выпустило наибольшее число книг толще 50 страниц
**Вывод:** 
- Издательство, выпустившее наибольшее число книг толще 50 страниц — Penguin Books. Это издательство выпустило 42 книги.

In [9]:
# чтобы выполнить SQL-запрос, используем Pandas
query = '''
           SELECT p.publisher "Издательство",
                  COUNT(DISTINCT b.book_id) "Количество книг"
           FROM publishers p
           LEFT JOIN books b ON b.publisher_id=p.publisher_id
           WHERE b.num_pages > 50
           GROUP BY p.publisher
           ORDER BY "Количество книг" DESC
           LIMIT 1
        '''

con=engine.connect()

pd.io.sql.read_sql(sql=text(query), con = con)

Издательство  Количество книг
0  Penguin Books               42

### Автор с самой высокой средней оценкой книг для книг с 50 и более оценками
**Вывод:**  
- Автор с самой высокой средней оценкой книг для книг с 50 и более оценками — J.K. Rowling/Mary GrandPré. Средняя оценка автора — 4.29.

In [10]:
# чтобы выполнить SQL-запрос, используем Pandas
query = '''
           SELECT a.author "Автор", ROUND(AVG(r.rating), 2) "Средняя оценка"
           FROM authors a
           JOIN books b ON a.author_id=b.author_id 
           AND b.book_id IN (SELECT book_id
                             FROM ratings
                             GROUP BY book_id
                             HAVING COUNT(DISTINCT rating_id) >= 50)
           LEFT JOIN ratings r ON b.book_id=r.book_id
           GROUP BY a.author_id
           ORDER BY "Средняя оценка" DESC
           LIMIT 1
                      
        '''

con=engine.connect()

pd.io.sql.read_sql(sql=text(query), con = con)

Автор  Средняя оценка
0  J.K. Rowling/Mary GrandPré            4.29

### Среднее количество обзоров от пользователей, которые поставили больше 48 оценок
**Вывод:** 
- Среднее количество обзоров от пользователей, которые поставили больше 48 оценок — 24.

In [11]:
# чтобы выполнить SQL-запрос, используем Pandas
query = '''
           SELECT AVG(count):: int "Количество обзоров"
           FROM (SELECT username, COUNT(review_id)
                 FROM reviews
                 WHERE username IN (SELECT username
                                    FROM ratings
                                    GROUP BY username
                                    HAVING COUNT(rating) > 48) 
                 GROUP BY username) t
        '''

con=engine.connect()

pd.io.sql.read_sql(sql=text(query), con = con)

Количество обзоров
0                  24

## Вывод
Был проведен анализ базы данных. База содержит следующие таблицы:
- **`books`** — содержит данные о книгах
- **`authors`** — содержит данные об авторах
- **`publishers`** — содержит данные об издательствах
- **`atings`** — содержит данные о пользовательских оценках книг

В результате исследования получены следующие **выводы:**  
- После 1 января 2000 года вышло 819 книг.
- Всего в базе представлено 1000 книг. 
- Самое большое количество обзоров написано для книги Twilight (7 обзоров). Ее средняя оценка — 3.66.
- 6 обзоров написано для 14 книг. Среди них книги с самым высоким рейтингом это:
    - Harry Potter and the Prisoner of Azkaban — 4.41
    - Harry Potter and the Chamber of Secrets — 4.29
    - The Book Thief — 4.26
- Издательство, выпустившее наибольшее число книг толще 50 страниц — Penguin Books. Это издательство выпустило 42 книги.
- Автор с самой высокой средней оценкой книг для книг с 50 и более оценками — J.K. Rowling/Mary GrandPré. Средняя оценка автора — 4.29.
- Среднее количество обзоров от пользователей, которые поставили больше 48 оценок — 24.